---
title: "Nintendo reviews from Amazon.com."
author: "Zinaida Dvoskina"
output:
  word_document: default
  html_document: default
  pdf_document: default
fontsize: 10 pt
---

```{r}
library(formatR)
knitr::opts_chunk$set(warning = FALSE)
```

```{r}

library(readxl)
Nintendo_Amazon_reviews_LIWC2015_results_final <- read_excel("Nintendo Amazon reviews LIWC2015 results final.xlsx")

Amazon_reviews <- 
  Nintendo_Amazon_reviews_LIWC2015_results_final [c(
  "id","item","item_name","review_date","rating","title", "review","review_language","Tone")]

Amazon_reviews_ENG = Amazon_reviews[which(Amazon_reviews$review_language == "ENG"),]
Amazon_reviews_ES = Amazon_reviews[which(Amazon_reviews$review_language == "ES"),]

ENG_rating = Amazon_reviews_ENG$rating
ES_rating = Amazon_reviews_ES$rating

library(plotrix)
library(graphics)
multhist(list(ENG_rating,ES_rating),breaks=seq(0.5,5.5,by=1),probability=TRUE,
         main = "ratings of reviews written in English 
         versus in Spanish",
         legend.text = c("ENG", "ES"),
         args.legend = list(x="top"),
         col = c("blue", "red"))

library(tidytext)
library(dplyr)

# unnest tokens:
tokenized_reviews <- Amazon_reviews_ENG %>%
                  unnest_tokens(word, review)%>% 
                  anti_join(get_stopwords())

tokenized_reviews <- tokenized_reviews %>%
                  filter(!word %in% c("nintendo", "switch", "console", "consoles", "game", "games", "play"))

library(wordcloud)
cloud <- tokenized_reviews %>% count(word, name="freq", sort=TRUE)

"Amazon Reviews for Nintendo brand:
the 3 current consoles on the market:
Switch,
Switch OLED,
Switch Lite
and 3 top games by sales according to Nintendo itself:
Mario Kart 8 Deluxe,
Animal Crossing New Horizons,
Super Smash Bros. Ultimate."
wordcloud(words=cloud$word, freq=cloud$freq, max.words=100)

games <- tokenized_reviews[which(tokenized_reviews$item == "game"),]
games_cloud <- games %>% count(word, name="freq", sort=TRUE)

consoles <- tokenized_reviews[which(tokenized_reviews$item == "game"),]
consoles_cloud <- consoles %>% count(word, name="freq", sort=TRUE)

"Reviews for games vs Reviews for consoles"
par(mfrow = c(1,2), mar = c(0.1,0.1,0.1,0.1))
wordcloud(words=games_cloud$word, freq=games_cloud$freq, max.words=25,colors=c("deeppink"))
wordcloud(words=consoles_cloud$word, freq=consoles_cloud$freq, max.words=25, colors=c("blue"))

animal_crossing <- tokenized_reviews[which(tokenized_reviews$item_name == "Animal Crossing: New Horizons"),]
animal_crossing_cloud <- animal_crossing %>% count(word, name="freq", sort=TRUE)

mario_kart <- tokenized_reviews[which(tokenized_reviews$item_name == "Mario Kart 8 Deluxe"),]
mario_kart_cloud <- mario_kart %>% count(word, name="freq", sort=TRUE)

super_smash_bros <- tokenized_reviews[which(tokenized_reviews$item_name == "Super Smash Bros. Ultimate"),]
super_smash_bros_cloud <- super_smash_bros %>% count(word, name="freq", sort=TRUE)

"Reviews for Animal Crossing: New Horizons vs Reviews for Mario Kart 8 Deluxe vs Reviews for Super Smash Bros. Ultimate"
par(mfrow = c(1,3), mar = c(0.1,0.1,0.1,0.1))
wordcloud(words=animal_crossing_cloud$word, freq=animal_crossing_cloud$freq, max.words=25,colors=c("deeppink"))
wordcloud(words=mario_kart_cloud$word, freq=mario_kart_cloud$freq, max.words=25, colors=c("gold"))
wordcloud(words=super_smash_bros_cloud$word, freq=super_smash_bros_cloud$freq, max.words=25, colors=c("blue"))

switch <- tokenized_reviews[which(tokenized_reviews$item_name == "Switch"),]
switch_cloud <- switch %>% count(word, name="freq", sort=TRUE)

switch_lite <- tokenized_reviews[which(tokenized_reviews$item_name == "Switch - Lite"),]
switch_lite_cloud <- switch_lite %>% count(word, name="freq", sort=TRUE)

switch_oled <- tokenized_reviews[which(tokenized_reviews$item_name == "Switch – OLED Model"),]
switch_oled_cloud <- switch_oled %>% count(word, name="freq", sort=TRUE)

"Reviews for Switch vs Reviews for Switch - Lite vs Reviews for Switch – OLED Model"
par(mfrow = c(1,3), mar = c(0.1,0.1,0.1,0.1))
wordcloud(words=switch_cloud$word, freq=switch_cloud$freq, max.words=25,colors=c("deeppink"))
wordcloud(words=switch_lite_cloud$word, freq=switch_lite_cloud$freq, max.words=25, colors=c("gold"))
wordcloud(words=switch_oled_cloud$word, freq=switch_oled_cloud$freq, max.words=25, colors=c("blue"))

rating_1 <- tokenized_reviews[which(tokenized_reviews$rating == 1),]
rating_1_cloud <- rating_1 %>% count(word, name="freq", sort=TRUE)
rating_2 <- tokenized_reviews[which(tokenized_reviews$rating == 2),]
rating_2_cloud <- rating_2%>% count(word, name="freq", sort=TRUE)
rating_3 <- tokenized_reviews[which(tokenized_reviews$rating == 3),]
rating_3_cloud <- rating_3 %>% count(word, name="freq", sort=TRUE)
rating_4 <- tokenized_reviews[which(tokenized_reviews$rating == 4),]
rating_4_cloud <- rating_4 %>% count(word, name="freq", sort=TRUE)
rating_5 <- tokenized_reviews[which(tokenized_reviews$rating == 5),]
rating_5_cloud <- rating_5 %>% count(word, name="freq", sort=TRUE)

"Reviews by rating"
par(mfrow = c(1,5), mar = c(0.1,0.1,0.1,0.1))
wordcloud(words=rating_1_cloud$word, freq=rating_1_cloud$freq, max.words=25,colors=c("red"))
wordcloud(words=rating_2_cloud$word, freq=rating_2_cloud$freq, max.words=25,colors=c("orange"))
wordcloud(words=rating_3_cloud$word, freq=rating_3_cloud$freq, max.words=25,colors=c("gold"))
wordcloud(words=rating_4_cloud$word, freq=rating_4_cloud$freq, max.words=25,colors=c("green"))
wordcloud(words=rating_5_cloud$word, freq=rating_5_cloud$freq, max.words=25,colors=c("dark green"))

mean(tokenized_reviews$Tone)

negative <- tokenized_reviews[which(tokenized_reviews$Tone <mean(Amazon_reviews_ENG$Tone)),]
negative_cloud <- negative %>% count(word, name="freq", sort=TRUE)

positive <- tokenized_reviews[which(tokenized_reviews$Tone >mean(Amazon_reviews_ENG$Tone)),]
positive_cloud <- positive %>% count(word, name="freq", sort=TRUE)

"Reviews with tone above/below average usually contain these words"
par(mfrow = c(1,2), mar = c(0.1,0.1,0.1,0.1))
wordcloud(words=negative_cloud$word, freq=cloud$freq, max.words=25, colors=c("red"))
wordcloud(words=positive_cloud$word, freq=cloud$freq, max.words=25,colors=c("dark green"))
```